_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 51
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.11
            "6": 4.50.0.dev0
            "8":
                - 2
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 16
dataset:
    value: ILSVRC/imagenet-1k(train[:1%])
learning_rate:
    value: 0.0001
loss_fn:
    value: MSE Loss
model_name:
    value: SRResNet
num_epochs:
    value: 10
optimizer:
    value: Adam
scale_factor:
    value: 4
